---

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
  sql:
    init:
      mode: always
  profiles:
    default: development

logging:
  level:
    root: INFO

#api-key: ${API_KEY}
api-key: "c0ca5aaa0emsh2ceea15e6facedcp101d54jsn7e756f330ba5"
translate-url: "https://google-translate1.p.rapidapi.com/language/translate/v2"
api-url: "https://google-translate1.p.rapidapi.com/language/translate/v2/languages"
